version: "3.2"
services:
  frontend-dev:
    container_name: impera-frontend-dev
    restart: always
    image: impera-frontend:latest
    ports:
      - "3001:3000"
    environment:
      - BASE_URI=https://dev.imperaonline.de

  frontend-production:
    container_name: impera-frontend-production
    restart: always
    image: impera-frontend:production
    ports:
      - "3000:3000"
    environment:
      # - BASE_URI=https://www.imperaonline.de # this is the default
