name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: dist
  deploy:
    needs: build
    runs-on: windows-latest

    steps:      
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: build
          path: ./dist
      - name: Replace base uris in deployment
        uses: cschleiden/replace-tokens@master
        with:
          files: '["./dist/**/*.js"]'
          BaseUri: https://dev.imperaonline.de/
          ImageBaseUri: https://static.imperaonline.de/maps/
      - run: ./scripts/deployFrontend.ps1 -Source './dist' -Destination '$env:Website/$env:DestFolder' -AdditionalArguments "-verbose -enableRule:DoNotDeleteRule" -Username $env:Login -Password $env:Password -AuthType 'basic' -DestinationComputer 'https://imperaonline.de:8172/msdeploy.axd?site=$env:Website'
        env: 
          Website: dev.imperaonline.de
          DestFolder: wwwroot
          Login: ${{ secrets.Login }}        
          Password: ${{ secrets.Password }}
          AppPool: dev.imperaonline.de(domain)(4.0)(pool)