name: Prod Deployment

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build
      - name: Replace base uris in deployment
        uses: cschleiden/replace-tokens@master
        with:
          files: '["./.next/**/*.js"]'
        env:
          BaseUri: https://www.imperaonline.de
          ImageBaseUri: https://static.imperaonline.de/maps/
      - run: ./scripts/deployFrontend.ps1 -Source "${env:GITHUB_WORKSPACE}" -Destination "${env:Website}/${env:DestFolder}" -AdditionalArguments "-verbose -enableRule:DoNotDeleteRule" -Username ${env:Login} -Password ${env:Password} -AuthType "basic" -DestinationComputer "https://imperaonline.de:8172/msdeploy.axd?site=${env:Website}"
        env:
          Website: imperaonline.de
          Login: ${{ secrets.Login }}
          Password: ${{ secrets.Password }}
          AppPool: imperaonline.de(domain)(4.0)(pool)